### ISSUE TITLE
json: cannot unmarshal bool into Go struct field CommitInfo.commitInfo.operationParameters of type string

### ISSUE THREAD

**Issue by maxrem** [csimplestring/delta-go#50]
Hello!

I'm getting this error:
```
delta.ForTable: fail to get protocol and metadata when initializing snapshots: : json: cannot unmarshal bool into Go struct field CommitInfo.commitInfo.operationParameters of type string
```

In the _delta_log json:
```json
{"operationParameters":{"mode":"Overwrite","statsOnLoad":false,"partitionBy":"[]"}}
```

Looks like `statsOnLoad` can't be unmarshalled.

**Comment by csimplestring** [comment]
Which version of the delta are you using ? I suspect the table is a newer version that this library does not support.

**Comment by maxrem** [comment]
I'm not sure which version we're using. I have to ask my team, but I think it's a recent one.

It looks like the operation parameters is a `Map[String, Any]` in the [current Delta Lake code](https://github.com/delta-io/delta/blob/25a42df8b68a944490a38dcd838acff0c438d517/spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala#L45). Can I make a PR to change it to that in this library too?

Thanks!

**Comment by maxrem** [comment]
We're using Delta Lake v2.4.0

**Comment by csimplestring** [comment]
> I'm not sure which version we're using. I have to ask my team, but I think it's a recent one.
> 
> It looks like the operation parameters is a `Map[String, Any]` in the [current Delta Lake code](https://github.com/delta-io/delta/blob/25a42df8b68a944490a38dcd838acff0c438d517/spark/src/main/scala/org/apache/spark/sql/delta/DeltaOperations.scala#L45). Can I make a PR to change it to that in this library too?
> 
> Thanks!

sure, waiting for your contribution.
